-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.2
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-json
-   repo: git://github.com/strataconsulting/pre-commit-terraform
    sha: v1.2.0-st1
    hooks:
    -   id: terraform_fmt
